### ISSUE TITLE
Your mobs are horribly laggy (at least underground)

### ISSUE THREAD

**Issue by PineappleCat22** [TheSlayerMC/Journey-1.12#46]
Every time I travel underground my fps goes from 250 to 50. Using lag goggles I have discovered that your cave mobs are creating an excessive amount of lag.
![2020-05-17_09 25 05](https://user-images.githubusercontent.com/59720426/82154081-7fe04100-9820-11ea-82c3-451748d90b65.png)
![2020-05-17_09 24 44](https://user-images.githubusercontent.com/59720426/82154093-8ec6f380-9820-11ea-9f4a-5948f0e1a454.png)
![2020-05-17_09 12 23](https://user-images.githubusercontent.com/59720426/82154098-92f31100-9820-11ea-83d0-f0cd6561d5d1.png)
![2020-05-17_09 24 51](https://user-images.githubusercontent.com/59720426/82154104-9b4b4c00-9820-11ea-9042-9804a4151c82.png)
![2020-05-17_09 25 01](https://user-images.githubusercontent.com/59720426/82154113-a0a89680-9820-11ea-919b-174913aef42f.png)

I hope you can figure out whats going on because your mod is really awesome and I hate to have to remove it due to performance issues

**Comment by TimeConqueror** [comment]
I checked Caveling Render and didn't find any 'lag-causing' code. 

May you check it only with the mod Journey into The Light installed?
Before checking close your F3 debug menu (because mob health is only rendered when it is enabled) - it may cause lag due to rendering lag-diagram.
And provide LagGoogles screen about full FPS data, your F3 screen and your latest.log.

Thanks in advance.

**Comment by PineappleCat22** [comment]
![2020-05-17_10 09 45](https://user-images.githubusercontent.com/59720426/82155104-4ced7b80-9827-11ea-9849-5b81474525a3.png)
![2020-05-17_10 13 15](https://user-images.githubusercontent.com/59720426/82155112-537bf300-9827-11ea-9426-5fb2458f5793.png)
![2020-05-17_10 13 18](https://user-images.githubusercontent.com/59720426/82155114-57a81080-9827-11ea-962c-66af98be1261.png)
![image](https://user-images.githubusercontent.com/59720426/82155119-6262a580-9827-11ea-973c-47e8d85b0e32.png)
https://paste.ee/p/2Ybzd
Ran a few tests, set video settings to lowest, while the fps is still pretty solid there is still an amount of lag from the mobs, as well as a few model loading errors in the log in the paste.ee link

**Comment by PineappleCat22** [comment]
![2020-05-17_10 18 54](https://user-images.githubusercontent.com/59720426/82155179-d604b280-9827-11ea-8f90-fba6b6a96eb0.png)
screenshot without f3 open which i forgot to include

**Comment by TimeConqueror** [comment]
As I see, mobs without Health rendering are pretty normal for world to render (11 milliseconds as maximum on the last screen)

As for Lag Googles: To my mind, it shows color levels for entity lag-tracking in a weird way. Some mobs can eventually increase lags, as you can see with Pigs due to their big amount for neraby chunks.

Btw, I'll review all mobs someday, one by one to find lag-causing code.

As for this issue:
I'll recommend you to decrease RAM, which you are applying to Minecraft. Because too much memory is worse than not so much. Applying 30GB isntead of 6GB is not good.

What's your RAM limit for the computer? Maybe you exceed limit?

Also as I know, mob particles, for example, Floro ones may cause lag. We know about it and will fix as soon as we have time for it. So it (or other projectiles) can be a reason for your lags.

**Comment by PineappleCat22** [comment]
My pc ram is 32 gb, I set the ram for all multimc instances to 22 gb, not sure why it decides to allocate more.
